In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
import h2o
from h2o.estimators import H2ORandomForestEstimator

In [7]:
train_data = pd.read_csv('../data/train.csv')
train_data

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,40,Self-emp-not-inc,223881,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,70,United-States,>50K
1,30,Private,149118,HS-grad,9,Divorced,Craft-repair,Not-in-family,White,Female,0,0,40,United-States,<=50K
2,46,Private,109209,Some-college,10,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,>50K
3,32,Private,229566,Assoc-voc,11,Married-civ-spouse,Other-service,Husband,White,Male,0,0,60,United-States,>50K
4,54,?,148657,Preschool,1,Married-civ-spouse,?,Wife,White,Female,0,0,40,Mexico,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,40,Private,130834,Some-college,10,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
24996,31,Local-gov,33124,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,<=50K
24997,38,Federal-gov,190895,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,?,>50K
24998,23,Private,420973,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,40,United-States,<=50K
24999,60,Private,88055,10th,6,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K

In [8]:
test_data = pd.read_csv('../data/test.csv')
test_data

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country
0,31,Private,176711,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,38,United-States
1,40,Private,120277,Some-college,10,Never-married,Sales,Not-in-family,White,Male,0,0,40,United-States
2,43,Private,299197,Some-college,10,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States
3,70,Self-emp-inc,188260,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,16,United-States
4,51,Private,254211,Bachelors,13,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,20,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7159,37,Self-emp-not-inc,75050,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,55,United-States
7160,36,Private,156780,HS-grad,9,Never-married,Sales,Other-relative,Asian-Pac-Islander,Female,0,0,40,?
7161,34,Private,381153,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States
7162,59,Private,294395,Masters,14,Widowed,Prof-specialty,Not-in-family,White,Female,0,0,40,United-States
7163,24,State-gov,506329,Some-college,10,Never-married,Adm-clerical,Own-child,Asian-Pac-Islander,Male,0,0,40,?

In [10]:
x = train_data.drop(columns=['income'])
y = train_data['income']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=313)

In [35]:
h2o.init()

x_train_h2o = h2o.H2OFrame(pd.concat([x_train, y_train], axis = 1))
x_test_h2o = h2o.H2OFrame(x_test)
traget = 'income'

model = H2ORandomForestEstimator(ntrees = 100 , sample_rate = 0.7)
model.train(x = list(x.columns), y = traget, training_frame = x_train_h2o)

Checking whether there is an H2O instance running at http://localhost:54321 . connected.
Warning: Your H2O cluster version is too old (2 years, 7 months and 23 days)!Please download and install the latest version from http://h2o.ai/download/

--------------------------  ---------------------------------
H2O_cluster_uptime:         1 min 13 secs
H2O_cluster_timezone:       Asia/Tehran
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.36.1.4
H2O_cluster_version_age:    2 years, 7 months and 23 days !!!
H2O_cluster_name:           H2O_from_python_Ali_jt4fbk
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.943 Gb
H2O_cluster_total_cores:    12
H2O_cluster_allowed_cores:  12
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.9.7 final
--------------------------  ---------------------------------

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
drf Model Build progress: |██████████████████████████████████████████████████████| (done) 100%
Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  DRF_model_python_1743064942915_2


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,100.0,100.0,2135789.0,20.0,20.0,20.0,1372.0,1955.0,1640.46

ModelMetricsBinomial: drf
** Reported on train data. **

MSE: 0.09835614174608881
RMSE: 0.3136178275323149
LogLoss: 0.33916529472768137
Mean Per-Class Error: 0.18772966610773392
AUC: 0.9106958171340499
AUCPR: 0.7943053886471358
Gini: 0.8213916342680998

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.3714955422174396:

            <=50K    >50K   Error               Rate
0  <=50K  13316.0  1830.0  0.1208   (1830.0/15146.0)
1   >50K   1236.0  3618.0  0.2546    (1236.0/4854.0)
2  Total  14552.0  5448.0  0.1533   (3066.0/20000.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold         value    idx
0                        max f1   0.371496      0.702388  212.0
1                        max f2   0.169575      0.787055  303.0
2                  max f0point5   0.648353      0.736147  113.0
3                  max accuracy   0.533073      0.859950  151.0
4                 max precision   0.999955      1.000000    0.0
5                    max recall   0.000005      1.000000  399.0
6               max specificity   0.999955      1.000000    0.0
7              max absolute_mcc   0.453161      0.603735  180.0
8    max min_per_class_accuracy   0.288811      0.820148  248.0
9   max mean_per_class_accuracy   0.250090      0.823153  267.0
10                      max tns   0.999955  15146.000000    0.0
11                      max fns   0.999955   4518.000000    0.0
12                      max fps   0.000005  15146.000000  399.0
13                      max tps   0.000005   4854.000000  399.0
14                      max tnr   0.999955      1.000000    0.0
15                      max fnr   0.999955      0.930779    0.0
16                      max fpr   0.000005      1.000000  399.0
17                      max tpr   0.000005      1.000000  399.0

Gains/Lift Table: Avg response rate: 24.27 %, avg score: 24.62 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.0158,1.000000,4.120313,4.120313,1.000000,1.000000,1.000000,1.000000,0.065101,0.065101,312.031314,312.031314,0.065101
1,2,0.0200,0.994866,4.120313,4.120313,1.000000,0.997194,1.000000,0.999411,0.017305,0.082406,312.031314,312.031314,0.082406
2,3,0.0300,0.967748,4.037907,4.092844,0.980000,0.981508,0.993333,0.993443,0.040379,0.122785,303.790688,309.284439,0.122521
3,4,0.0400,0.942684,3.955501,4.058508,0.960000,0.957757,0.985000,0.984522,0.039555,0.162340,295.550062,305.850845,0.161548
4,5,0.0500,0.913046,3.955501,4.037907,0.960000,0.927582,0.980000,0.973134,0.039555,0.201895,295.550062,303.790688,0.200575
5,6,0.1000,0.759497,3.456943,3.747425,0.839000,0.837983,0.909500,0.905558,0.172847,0.374742,245.694273,274.742480,0.362792
6,7,0.1500,0.626651,2.711166,3.402005,0.658000,0.692553,0.825667,0.834557,0.135558,0.510301,171.116605,240.200522,0.475770
7,8,0.2000,0.511715,2.237330,3.110836,0.543000,0.567952,0.755000,0.767906,0.111867,0.622167,123.733004,211.083642,0.557464
8,9,0.3000,0.334321,1.590441,2.604038,0.386000,0.413814,0.632000,0.649875,0.159044,0.781211,59.044087,160.403791,0.635430
9,10,0.4000,0.205830,1.032138,2.211063,0.250500,0.268427,0.536625,0.554513,0.103214,0.884425,3.213844,121.106304,0.639674
10,11,0.5000,0.104782,0.628348,1.894520,0.152500,0.152036,0.459800,0.474018,0.062835,0.947260,-37.165225,89.451998,0.590598
11,12,0.6001,0.040000,0.312831,1.630686,0.075924,0.069482,0.395767,0.406539,0.031314,0.978574,-68.716903,63.068551,0.499768
12,13,0.7000,0.004986,0.136106,1.417388,0.033033,0.020859,0.344000,0.351497,0.013597,0.992171,-86.389356,41.738772,0.385807
13,14,1.0000,0.000000,0.026095,1.000000,0.006333,0.000403,0.242700,0.246169,0.007829,1.000000,-97.390468,0.000000,0.000000

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_auc,training_pr_auc,training_lift,training_classification_error
0,,2025-03-27 13:14:00,0.016 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,,2025-03-27 13:14:00,0.158 sec,1.0,0.393285,3.792762,0.795371,0.561897,2.696844,0.189154
2,,2025-03-27 13:14:01,0.440 sec,2.0,0.382891,3.295300,0.815929,0.588534,2.764987,0.185785
3,,2025-03-27 13:14:01,0.596 sec,3.0,0.380599,3.104580,0.818549,0.593736,2.815259,0.189976
4,,2025-03-27 13:14:01,0.653 sec,4.0,0.371796,2.669246,0.829859,0.617539,2.962712,0.183937
5,,2025-03-27 13:14:01,0.731 sec,5.0,0.367217,2.421786,0.835870,0.630398,3.043361,0.184131
6,,2025-03-27 13:14:01,0.796 sec,6.0,0.361435,2.139837,0.843861,0.645743,3.128995,0.182801
7,,2025-03-27 13:14:01,0.920 sec,7.0,0.356848,1.885278,0.849911,0.660126,3.240365,0.181224
8,,2025-03-27 13:14:01,0.999 sec,8.0,0.354571,1.728607,0.853587,0.668073,3.299291,0.175423
9,,2025-03-27 13:14:01,1.061 sec,9.0,0.349756,1.507879,0.859618,0.685069,3.429563,0.179302
10,,2025-03-27 13:14:01,1.155 sec,10.0,0.345129,1.322835,0.866066,0.701606,3.550930,0.179281
11,,2025-03-27 13:14:01,1.234 sec,11.0,0.341625,1.168157,0.871735,0.711327,3.619798,0.178382
12,,2025-03-27 13:14:01,1.305 sec,12.0,0.338784,1.054388,0.875758,0.719946,3.679974,0.167894
13,,2025-03-27 13:14:01,1.369 sec,13.0,0.337027,0.979441,0.878217,0.725267,3.724632,0.175819
14,,2025-03-27 13:14:01,1.407 sec,14.0,0.334848,0.929017,0.880656,0.730751,3.750062,0.169387
15,,2025-03-27 13:14:02,1.470 sec,15.0,0.333116,0.869053,0.882700,0.736421,3.794271,0.168267
16,,2025-03-27 13:14:02,1.517 sec,16.0,0.331506,0.803645,0.885211,0.742358,3.841159,0.160052
17,,2025-03-27 13:14:02,1.580 sec,17.0,0.330980,0.780591,0.886095,0.742931,3.834019,0.158074
18,,2025-03-27 13:14:02,1.627 sec,18.0,0.329705,0.726453,0.888364,0.746302,3.859997,0.159107
19,,2025-03-27 13:14:02,1.674 sec,19.0,0.328757,0.701089,0.889493,0.748860,3.873435,0.161363

See the whole table with table.as_data_frame()

Variable Importances:

          variable  relative_importance  scaled_importance  percentage
0   marital.status         32018.589844           1.000000    0.151511
1     capital.gain         26644.167969           0.832147    0.126079
2     relationship         25028.136719           0.781675    0.118432
3       occupation         21445.373047           0.669779    0.101479
4              age         20770.021484           0.648686    0.098283
5    education.num         17399.417969           0.543416    0.082333
6        education         14330.038086           0.447554    0.067809
7           fnlwgt         13414.477539           0.418959    0.063477
8   hours.per.week         12576.173828           0.392777    0.059510
9        workclass          8055.617676           0.251592    0.038119
10    capital.loss          7879.672852           0.246097    0.037286
11  native.country          6105.175293           0.190676    0.028889
12             sex          2950.288086           0.092143    0.013961
13            race          2711.836670           0.084696    0.012832

In [37]:
y_pred_h2o = model.predict(x_test_h2o)
y_pred = h2o.as_list(y_pred_h2o['predict'], use_pandas=True).values.flatten()

y_test_numeric = y_test.replace({'<=50K': 0, '>50K': 1}).values
y_pred_numeric = pd.Series(y_pred).replace({'<=50K': 0, '>50K': 1}).values

print(f1_score(y_test_numeric, y_pred_numeric))

drf prediction progress: |███████████████████████████████████████████████████████| (done) 100%
0.7247191011235955

In [43]:
test_data_h2o = h2o.H2OFrame(test_data)
y_pred = model.predict(test_data_h2o)
submission = h2o.as_list(y_pred['predict'], use_pandas=True).values
submission

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
drf prediction progress: |███████████████████████████████████████████████████████| (done) 100%

D:\quera\qenv\lib\site-packages\h2o\job.py:83: UserWarning: Test/Validation dataset column 'native.country' has levels not trained on: ["Holand-Netherlands"]
  warnings.warn(w)

array([['<=50K'],
       ['<=50K'],
       ['<=50K'],
       ...,
       ['<=50K'],
       ['<=50K'],
       ['<=50K']], dtype=object)

In [44]:
submission = pd.DataFrame(submission)
submission.columns =['income']
submission

     income
0     <=50K
1     <=50K
2     <=50K
3      >50K
4     <=50K
...     ...
7159  <=50K
7160  <=50K
7161  <=50K
7162  <=50K
7163  <=50K

[7164 rows x 1 columns]