In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_csv('../data/train_data.csv')
train_data.isna().sum()

Created                      0
CancelTime               85691
DepartureTime                0
BillID                       0
TicketID                     0
ReserveStatus                0
UserID                   58474
Male                         0
Price                        0
CouponDiscount               0
From                         0
To                           0
Domestic                     0
VehicleType               7544
VehicleClass             38450
TripReason                   0
Vehicle                      0
Cancel                       0
HashPassportNumber_p    100155
HashEmail                57933
BuyerMobile                  0
NationalCode                 0
dtype: int64

In [3]:
test_data = pd.read_csv('../data/test_data.csv')
test_data

,Created,CancelTime,DepartureTime,BillID,TicketID,ReserveStatus,UserID,Male,Price,CouponDiscount,...,To,Domestic,VehicleType,VehicleClass,Vehicle,Cancel,HashPassportNumber_p,HashEmail,BuyerMobile,NationalCode
0,2022-07-22 12:52:35.293,NaN,2022-08-03 17:00:00,38372770,7429183.0,3,NaN,False,1220000.0,0.0,...,اصفهان,1,ماهانVIP مانیتوردار کاوه,True,Bus,0,NaN,7ec2bc45a1a56014c60beb9e6ae72e748563f270b5961e...,855578545022,752371627
1,2022-05-16 10:55:29.397,2022-05-18 11:35:15.643,2022-05-19 17:00:00,37348034,7147402.0,5,NaN,True,2830000.0,0.0,...,قم,1,VIP 2+1 / سیستم تهویه مطبوع / تخت شو,True,Bus,1,NaN,09731a27ab7323fa8a65a5d61a6f6cdf5b127a5d89d1af...,687891042993,926996211
2,2022-02-13 16:10:33.870,NaN,2022-02-15 22:45:00,36058084,6817410.0,3,NaN,True,1480000.0,0.0,...,اردبیل,1,25 نفره (VIP),True,Bus,0,NaN,NaN,515831406373,890191812
3,2022-05-01 17:56:18.530,NaN,2022-05-06 14:30:00,37140430,7093047.0,3,NaN,False,2450000.0,0.0,...,شیراز,1,Scania VIP 2+1,True,Bus,0,NaN,NaN,349742111820,941450742
4,2022-05-19 18:40:48.760,NaN,2022-05-21 12:30:00,37393459,2789874.0,2,135424.0,True,1965500.0,0.0,...,تهران,1,3 ستاره 6 تخته كوير,NaN,Train,0,NaN,a9b7344fa6dffcd85117f3b4209a379600a66019dbfb57...,63387630789,575541645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43288,2022-10-06 16:57:16.053,NaN,2022-10-07 21:00:00,39515216,7693401.0,3,NaN,True,800000.0,0.0,...,زاهدان,1,classicus 2+2,True,Bus,0,NaN,084471d0e58161bf494c8d540208e17d2b3cb0ea3eff70...,793972140866,560495589
43289,2022-06-14 13:19:26.413,NaN,2022-06-18 07:15:00,37773311,1055789.0,5,NaN,False,7827000.0,0.0,...,تهران,1,NaN,False,Plane,0,NaN,NaN,574095530769,194295556
43290,2022-10-23 15:48:03.947,NaN,2022-10-23 20:25:00,39714891,7747506.0,3,NaN,False,370000.0,0.0,...,قم,1,مارال تک صندلی ۳۰نفره,True,Bus,0,NaN,NaN,82614935547,704290882
43291,2022-09-18 21:18:01.730,2022-09-19 15:40:44.707,2022-09-20 20:00:00,39215621,7620724.0,5,950877.0,True,2520000.0,0.0,...,مسجدسلیمان,1,VIP 2+1 / شارژر یو اس بی / سیستم تهویه مطبوع ...,True,Bus,1,NaN,57f1cffdba91d23d66f923c5defcd40caa8d317f8bcfbc...,242545550300,513968890
43292,2022-07-27 22:08:17.510,2022-07-30 19:19:29.357,2022-08-03 21:00:00,38449571,7451530.0,5,633165.0,True,2150000.0,0.0,...,تهران,1,VIP درسا مانیتوردار با پک بهداشتی,True,Bus,1,NaN,NaN,965279078669,20749399

In [4]:
# Filling missing value
mod = train_data.groupby('Vehicle')['VehicleType'].transform(lambda x : x.mode()[0])
train_data['VehicleType'] = train_data.groupby('Vehicle')['VehicleType'].fillna(mod)
mod = train_data.groupby('VehicleType')['VehicleClass'].transform(lambda x: x.mode()[0] if not x.mode().empty else 0)
train_data['VehicleClass'] = train_data.groupby('VehicleType')['VehicleClass'].fillna(mod)
mod = test_data.groupby('Vehicle')['VehicleType'].transform(lambda x : x.mode()[0])
test_data['VehicleType'] = test_data.groupby('Vehicle')['VehicleType'].fillna(mod)
mod = test_data.groupby('VehicleType')['VehicleClass'].transform(lambda x: x.mode()[0] if not x.mode().empty else 0)
test_data['VehicleClass'] = test_data.groupby('VehicleType')['VehicleClass'].fillna(mod)

C:\Users\Ali\AppData\Local\Temp\ipykernel_13116\1977675697.py:3: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  train_data['VehicleType'] = train_data.groupby('Vehicle')['VehicleType'].fillna(mod)
C:\Users\Ali\AppData\Local\Temp\ipykernel_13116\1977675697.py:5: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  train_data['VehicleClass'] = train_data.groupby('VehicleType')['VehicleClass'].fillna(mod)
C:\Users\Ali\AppData\Local\Temp\ipykernel_13116\1977675697.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_data['VehicleClass'] = train_data.groupby('VehicleType')['VehicleClass'].fillna(mod)
C:\Users\Ali\AppData\Local\Temp\ipykernel_13116\1977675697.py:7: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  test_data['VehicleType'] = test_data.groupby('Vehicle')['VehicleType'].fillna(mod)
C:\Users\Ali\AppData\Local\Temp\ipykernel_13116\1977675697.py:9: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  test_data['VehicleClass'] = test_data.groupby('VehicleType')['VehicleClass'].fillna(mod)
C:\Users\Ali\AppData\Local\Temp\ipykernel_13116\1977675697.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_data['VehicleClass'] = test_data.groupby('VehicleType')['VehicleClass'].fillna(mod)

In [ ]:
# Feature Creation
train_data['DepartureTime_month'] = train_data['DepartureTime'].apply(lambda x: pd.to_datetime(x).month)
test_data['DepartureTime_month'] = test_data['DepartureTime'].apply(lambda x: pd.to_datetime(x).month)

train_data['DepartureTime_hour'] = train_data['DepartureTime'].apply(lambda x: pd.to_datetime(x).hour)
test_data['DepartureTime_hour'] = test_data['DepartureTime'].apply(lambda x: pd.to_datetime(x).hour)

train_data['Created_month'] = train_data['Created'].apply(lambda x: pd.to_datetime(x).month)
test_data['Created_month'] = test_data['Created'].apply(lambda x: pd.to_datetime(x).month)

train_data['Created_hour'] = train_data['Created'].apply(lambda x: pd.to_datetime(x).hour)
test_data['Created_hour'] = test_data['Created'].apply(lambda x: pd.to_datetime(x).hour)

In [ ]:
# Repalcing True False Values
train_data['Male'] = train_data['Male'].replace({True: 1, False: 0})
test_data['Male'] = test_data['Male'].replace({True: 1, False: 0})
train_data['VehicleClass'] = train_data['VehicleClass'].replace({True: 1, False: 0 ,np.nan:-1})
test_data['VehicleClass'] = test_data['VehicleClass'].replace({True: 1, False: 0 , np.nan:-1})
train_data['TripReason'] = train_data['TripReason'].replace({'Work': 1, 'Int': 0 })

In [ ]:
# Scaling
from sklearn.preprocessing import MinMaxScaler
scaler_coupon = MinMaxScaler()
scaler_price = MinMaxScaler()

train_data['CouponDiscount'] = scaler_coupon.fit_transform(train_data[['CouponDiscount']])
train_data['Price'] = scaler_price.fit_transform(train_data[['Price']])

test_data['CouponDiscount'] = scaler_coupon.transform(test_data[['CouponDiscount']])
test_data['Price'] = scaler_price.transform(test_data[['Price']])

In [ ]:
# Encoding
dummy = pd.get_dummies(train_data['Vehicle'], prefix = 'Vehicle')
train_data = pd.concat([train_data, dummy], axis=1)
train_data = train_data.drop('Vehicle', axis=1)

dummy = pd.get_dummies(test_data['Vehicle'], prefix = 'Vehicle')
test_data = pd.concat([test_data, dummy], axis=1)
test_data = test_data.drop('Vehicle', axis=1)

In [ ]:
# Dropping Useless Data
train_data.drop(columns = ['CancelTime','UserID','HashPassportNumber_p','HashEmail','BuyerMobile','NationalCode','DepartureTime','Created','BillID','TicketID','From', 'To','VehicleType'],inplace = True)
test_data.drop(columns = ['CancelTime','UserID','HashPassportNumber_p','HashEmail','BuyerMobile','NationalCode','DepartureTime','Created','BillID','TicketID','From', 'To','VehicleType'],inplace = True)
train_data

,ReserveStatus,Male,Price,CouponDiscount,Domestic,VehicleClass,TripReason,Cancel,DepartureTime_month,DepartureTime_hour,Created_month,Created_hour,Vehicle_Bus,Vehicle_InternationalPlane,Vehicle_Plane,Vehicle_Train
0,5,1,0.021060,0.002523,1,0,1,0,11,23,10,9,0,0,1,0
1,5,1,0.028587,0.000139,1,0,0,0,8,4,8,14,0,0,1,0
2,3,0,0.009121,0.000139,1,1,1,0,9,11,9,17,1,0,0,0
3,2,0,0.004033,0.000139,1,0,0,0,6,8,6,11,0,0,0,1
4,3,1,0.006863,0.000139,1,1,0,0,6,23,6,11,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101012,5,1,0.019243,0.000139,1,0,0,0,6,12,6,0,0,0,1,0
101013,2,1,0.006334,0.000139,1,0,1,0,11,15,10,20,0,0,0,1
101014,5,1,0.081795,0.000139,0,0,0,0,9,9,9,17,0,1,0,0
101015,3,1,0.006473,0.000139,1,1,1,0,9,17,9,13,1,0,0,0
101016,2,1,0.012152,0.000139,1,0,1,0,4,17,3,13,0,0,0,1

In [ ]:
# Data Selection
from sklearn.model_selection import train_test_split

x = train_data.drop(columns = ['TripReason']) 
y = train_data['TripReason']
x_train , x_test , y_train ,y_test  = train_test_split(x , y, test_size = 0.2,random_state = 535, stratify = y)

In [ ]:
# modeling 

import xgboost as xgb

model = xgb.XGBClassifier(max_depth = 7 ,learning_rate = 0.2 , n_estimators = 200 , subsample = 0.8 , min_child_weight = 1, gamma = 1 )
model.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=1, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.2, max_bin=256,
              max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
              max_depth=7, max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=200, n_jobs=0,
              num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [ ]:
# evaluate model
from sklearn.metrics import  f1_score, classification_report, confusion_matrix
y_pred = model.predict(x_test)
print(f1_score(y_test,y_pred))

0.8062729054802693

In [ ]:
# predict test samples
submission = model.predict(test_data)
submission = pd.DataFrame(submission)
submission.columns = ['TripReason']
submission['TripReason'].replace({1 : 'Work' , 0 : 'Int'} , inplace = True)
submission

      TripReason
0           Work
1           Work
2           Work
3           Work
4           Work
...          ...
43288       Work
43289       Work
43290       Work
43291       Work
43292        Int

[43293 rows x 1 columns]