In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_csv('../data/train_data.csv')
train_data

,Created,CancelTime,DepartureTime,BillID,TicketID,ReserveStatus,UserID,Male,Price,CouponDiscount,...,Domestic,VehicleType,VehicleClass,TripReason,Vehicle,Cancel,HashPassportNumber_p,HashEmail,BuyerMobile,NationalCode
0,2022-07-26 13:33:20.457,NaN,2022-07-26 16:30:00,38428546,7445571.0,3,NaN,True,1180000.0,0.0,...,1,VIPمانیتوردار-شارژراختصاصی تخت شو مارال (جدید)...,True,Work,Bus,0,NaN,NaN,302222356019,330024570
1,2022-10-27 23:07:01.837,2022-10-27 23:26:39.070,2022-10-29 09:45:00,39768762,7762719.0,5,NaN,False,1050000.0,0.0,...,1,classicus 2+2,True,Int,Bus,1,NaN,NaN,900764168521,995520696
2,2022-09-12 11:01:13.607,NaN,2022-10-03 18:35:00,39128001,2327596.0,5,800398.0,False,4674000.0,0.0,...,1,فوکر 100,False,Int,Plane,0,NaN,1c44d7a76b52341fa12dcfa993138576befcc9ebf01d14...,749804783291,979382950
3,2022-08-08 17:43:35.840,NaN,2022-08-08 22:30:00,38606546,7495440.0,3,NaN,True,1200000.0,0.0,...,1,VIPدرسا+مانیتوردار+شارژراختصاصی+پذیرایی,True,Work,Bus,0,NaN,NaN,781396205677,911237229
4,2022-11-01 15:12:56.823,NaN,2022-11-03 11:30:00,39822185,2356902.0,5,NaN,True,6222000.0,0.0,...,1,NaN,False,Work,Plane,0,NaN,bb38b345aec02255e31d178492907175c5984f2a1f5b59...,524576220177,727496008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101012,2022-10-27 21:41:35.803,NaN,2022-11-05 20:15:00,39767774,3082282.0,2,NaN,False,7200000.0,0.0,...,1,5ستاره بيزينس سلامت فدك,NaN,Int,Train,0,NaN,NaN,395081863564,789320493
101013,2022-09-24 15:51:11.993,NaN,2022-10-21 09:15:00,39319207,3026516.0,2,151423.0,False,4292000.0,0.0,...,1,4ستاره4تخته سپهر,NaN,Int,Train,0,NaN,3f28ed65a16d629747e4d27fab100b2b082fcbdf7ec831...,130026405332,866503410
101014,2022-08-12 13:46:20.480,NaN,2022-08-12 23:59:00,38653461,7508988.0,3,NaN,True,1320000.0,0.0,...,1,VIP 2+1 / مانیتوردار / سیستم تهویه مطبوع / تخ...,True,Int,Bus,0,NaN,NaN,784949357488,881677039
101015,2022-06-20 15:15:37.780,NaN,2022-06-25 10:10:00,37880627,1057205.0,5,641744.0,True,13000000.0,0.0,...,1,NaN,False,Work,Plane,0,NaN,750690ca99468f159eff6ad928cec4339b089af8c2e6dc...,766602541733,403505466
101016,2022-07-25 00:25:14.170,NaN,2022-07-25 21:00:00,38408696,7439771.0,3,857274.0,True,2150000.0,0.0,...,1,MAN VIP 2+1,True,Work,Bus,0,NaN,NaN,899439800471,593217954

In [3]:
test_data = pd.read_csv('../data/test_data.csv')
test_data

,Created,DepartureTime,BillID,TicketID,ReserveStatus,UserID,Male,Price,CouponDiscount,From,To,Domestic,VehicleType,VehicleClass,TripReason,Vehicle,HashPassportNumber_p,HashEmail,BuyerMobile,NationalCode
0,2022-07-08 12:04:46.290,2022-08-16 23:59:00,38166794,2890395.0,2,NaN,False,2043000.0,0.0,مشهد,تهران,1,3 ستاره 6 تخته پارسي,NaN,Int,Train,NaN,NaN,419509763088,660703096
1,2022-09-30 14:18:23.487,2022-09-30 23:59:00,39424175,7669420.0,3,NaN,False,1220000.0,0.0,تهران,اصفهان,1,V I P,True,Int,Bus,NaN,NaN,935955347521,960594437
2,2022-05-15 10:52:01.293,2022-06-06 17:40:00,37336619,2783057.0,2,800538.0,True,2132000.0,0.0,مشهد,تهران,1,4ستاره 4تخته سبز نوين,NaN,Int,Train,NaN,NaN,428059757595,854730165
3,2022-10-06 02:55:53.723,2022-10-14 19:45:00,39507715,7691289.0,5,950983.0,False,520000.0,0.0,تهران,سمنان,1,اسکانیا,True,Work,Bus,NaN,012dca1b2070c32e03238f49aa8f12a1a9ce580f8b1368...,515601565031,850531769
4,2022-03-12 13:46:40.300,2022-03-12 19:30:00,36422079,6901256.0,3,NaN,True,1180000.0,0.0,ارومیه,کرمانشاه,1,اسکانیا تک صندلی,True,Work,Bus,NaN,NaN,633910237635,893186872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43288,2022-09-25 15:33:09.793,2022-09-25 20:30:00,39338188,7647177.0,3,NaN,True,2480000.0,0.0,تهران,مشهد (خراسان ),1,وای پی تخت شو ۲۵نفره,True,Int,Bus,NaN,7091c8c24f3f57b98561de5d9a874cb91c3fd44371930a...,45595252975,158174797
43289,2022-07-16 19:58:15.300,2022-07-18 21:45:00,38298325,7406150.0,3,NaN,True,1330000.0,0.0,اصفهان,شیراز,1,اسکانیا درسا(مانیتور اختصاصی),True,Work,Bus,NaN,NaN,194871920550,384954737
43290,2022-06-16 18:14:40.673,2022-06-17 17:30:00,37823306,7274287.0,3,NaN,True,1290000.0,0.0,تهران,رودسر,1,مارال 25 نفره VIP,True,Int,Bus,NaN,NaN,687841588584,648554818
43291,2022-07-23 13:48:45.330,2022-08-23 21:05:00,38386540,2914007.0,2,724274.0,True,2810500.0,0.0,مشهد,تهران,1,4 ستاره 4 تخته غزال,NaN,Int,Train,NaN,a78e5ce63b34517a2c4e1d3ccd474241abe1993b49905c...,976918931561,779144272
43292,2022-08-14 11:04:39.597,2022-08-15 22:00:00,38674829,7514844.0,3,610090.0,True,1700000.0,0.0,خرم آباد (لرستان ),کرج,1,مان 25 نفره VIP,True,Int,Bus,NaN,NaN,251061924518,146816459

In [4]:
# do some preprocessing

In [5]:
# Drop useless data
train_data.drop(columns = ['CancelTime','UserID','HashPassportNumber_p','HashEmail','BuyerMobile','NationalCode'],inplace = True)
test_data.drop(columns = ['UserID','HashPassportNumber_p','HashEmail','BuyerMobile','NationalCode'],inplace = True)

In [6]:
# Fill missing values
mod = train_data.groupby('Vehicle')['VehicleType'].transform(lambda x : x.mode()[0])
train_data['VehicleType'] = train_data.groupby('Vehicle')['VehicleType'].fillna(mod)
mod = train_data.groupby('VehicleType')['VehicleClass'].transform(lambda x: x.mode()[0] if not x.mode().empty else 0)
train_data['VehicleClass'] = train_data.groupby('VehicleType')['VehicleClass'].fillna(mod)
mod = test_data.groupby('Vehicle')['VehicleType'].transform(lambda x : x.mode()[0])
test_data['VehicleType'] = test_data.groupby('Vehicle')['VehicleType'].fillna(mod)
mod = test_data.groupby('VehicleType')['VehicleClass'].transform(lambda x: x.mode()[0] if not x.mode().empty else 0)
test_data['VehicleClass'] = test_data.groupby('VehicleType')['VehicleClass'].fillna(mod)

C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\1647666053.py:3: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  train_data['VehicleType'] = train_data.groupby('Vehicle')['VehicleType'].fillna(mod)
C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\1647666053.py:5: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  train_data['VehicleClass'] = train_data.groupby('VehicleType')['VehicleClass'].fillna(mod)
C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\1647666053.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_data['VehicleClass'] = train_data.groupby('VehicleType')['VehicleClass'].fillna(mod)
C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\1647666053.py:7: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  test_data['VehicleType'] = test_data.groupby('Vehicle')['VehicleType'].fillna(mod)
C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\1647666053.py:9: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  test_data['VehicleClass'] = test_data.groupby('VehicleType')['VehicleClass'].fillna(mod)
C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\1647666053.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_data['VehicleClass'] = test_data.groupby('VehicleType')['VehicleClass'].fillna(mod)

In [7]:
train_data['family'] = train_data.groupby('BillID')['TicketID'].transform('count')
test_data['family'] = test_data.groupby('BillID')['TicketID'].transform('count')
train_data['is with family'] = (train_data.groupby('BillID')['family'].transform(lambda x: (x > 1).astype(int)))
test_data['is with family'] = (test_data.groupby('BillID')['family'].transform(lambda x: (x > 1).astype(int)))

In [8]:
train_data['blit_gap'] = (pd.to_datetime(train_data['DepartureTime'])- pd.to_datetime(train_data['Created'])).dt.days  
test_data['blit_gap'] = (pd.to_datetime(test_data['DepartureTime'])- pd.to_datetime(test_data['Created'])).dt.days

In [9]:
train_data['has discount'] = train_data['CouponDiscount'].apply(lambda x :(x > 1))
test_data['has discount'] = test_data['CouponDiscount'].apply(lambda x :(x > 1))
train_data['has discount'] = train_data['has discount'].replace({True: 1, False: 0})
test_data['has discount'] = test_data['has discount'].replace({True: 1, False: 0})

C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\1996747652.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_data['has discount'] = train_data['has discount'].replace({True: 1, False: 0})
C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\1996747652.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_data['has discount'] = test_data['has discount'].replace({True: 1, False: 0})

In [10]:
train_data['net_price'] = train_data['Price'] - train_data['CouponDiscount'] 
test_data['net_price'] = test_data['Price'] - test_data['CouponDiscount']

In [11]:
train_data['Male'] = train_data['Male'].replace({True: 1, False: 0})
test_data['Male'] = test_data['Male'].replace({True: 1, False: 0})
train_data['TripReason'] = train_data['TripReason'].replace({'Work': 1, 'Int': 0})
test_data['TripReason'] = test_data['TripReason'].replace({'Work': 1, 'Int': 0})

C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\2942434806.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_data['Male'] = train_data['Male'].replace({True: 1, False: 0})
C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\2942434806.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_data['Male'] = test_data['Male'].replace({True: 1, False: 0})
C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\2942434806.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_data['TripReason'] = train_data['TripReason'].replace({'Work': 1, 'Int': 0})
C:\Users\Ali\AppData\Local\Temp\ipykernel_14272\2942434806.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_data['TripReason'] = test_data['TripReason'].replace({'Work': 1, 'Int': 0})

In [12]:
from sklearn.preprocessing import MinMaxScaler
Scaler = MinMaxScaler()

train_data['CouponDiscount'] = Scaler.fit_transform(train_data[['CouponDiscount']])
train_data['Price'] = Scaler.fit_transform(train_data[['Price']])
train_data['net_price'] = Scaler.fit_transform(train_data[['net_price']])
test_data['CouponDiscount'] = Scaler.fit_transform(test_data[['CouponDiscount']])
test_data['Price'] = Scaler.fit_transform(test_data[['Price']])
test_data['net_price'] = Scaler.fit_transform(test_data[['net_price']])

In [13]:
from sklearn.preprocessing import LabelEncoder
Encoder = LabelEncoder()

Labels = ['From','To','Vehicle']
for i in Labels:
    train_data[i] = Encoder.fit_transform(train_data[i])
    test_data[i] = Encoder.fit_transform(test_data[i])

In [14]:
train_data.drop(columns = ['Created','DepartureTime','BillID','TicketID','CouponDiscount','VehicleType'],inplace = True)
test_data.drop(columns = ['Created','DepartureTime','BillID','TicketID','CouponDiscount','VehicleType'],inplace = True)
train_data['VehicleClass'] = train_data['VehicleClass'].astype(float)
test_data['VehicleClass'] = test_data['VehicleClass'].astype(float)

In [15]:
train_data

,ReserveStatus,Male,Price,From,To,Domestic,VehicleClass,TripReason,Vehicle,Cancel,family,is with family,blit_gap,has discount,net_price
0,3,1,0.006992,134,155,1,1.0,1,0,0,3,1,0,0,0.006992
1,5,0,0.006655,151,138,1,1.0,0,0,1,5,1,1,0,0.006655
2,5,0,0.016061,67,19,1,0.0,0,2,0,8,1,21,0,0.016061
3,3,1,0.007044,67,221,1,1.0,1,0,0,1,0,0,0,0.007044
4,5,1,0.020079,201,76,1,0.0,1,2,0,1,0,1,0,0.020079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101012,2,0,0.022617,168,76,1,0.0,0,3,0,3,1,8,0,0.022617
101013,2,0,0.015070,168,28,1,0.0,0,3,0,4,1,26,0,0.015070
101014,3,1,0.007356,134,28,1,1.0,0,0,0,1,0,0,0,0.007356
101015,5,1,0.037671,67,132,1,0.0,1,2,0,1,0,4,0,0.037671
101016,3,1,0.009510,18,76,1,1.0,1,0,0,1,0,0,0,0.009510

In [16]:
# Data Selection
from sklearn.model_selection import train_test_split

x = train_data.drop(columns = ['Cancel']) 
y = train_data['Cancel']
x_train , x_test , y_train ,y_test  = train_test_split(x , y)
x_train

,ReserveStatus,Male,Price,From,To,Domestic,VehicleClass,TripReason,Vehicle,family,is with family,blit_gap,has discount,net_price
77095,5,0,0.156235,10,22,0,0.0,0,1,4,1,20,0,0.156235
44213,3,1,0.010470,67,34,1,1.0,1,0,1,0,19,0,0.010470
74304,2,1,0.012548,55,218,1,0.0,0,3,9,1,12,0,0.012548
99344,3,0,0.006992,208,169,1,1.0,1,0,1,0,8,0,0.006992
58351,2,1,0.004111,67,196,1,0.0,1,3,1,0,3,0,0.004111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33178,2,0,0.011894,168,76,1,0.0,0,3,2,1,15,0,0.011894
37977,3,0,0.007901,134,34,1,1.0,1,0,1,0,3,0,0.007901
7417,5,1,0.028216,30,76,1,0.0,0,2,1,0,13,0,0.028216
8436,2,1,0.011027,30,76,1,0.0,1,3,1,0,1,0,0.011027
20800,3,1,0.007745,130,76,1,1.0,1,0,1,0,13,0,0.007745

In [17]:
# modeling
import xgboost as xgb
model = xgb.XGBClassifier(max_depth = 20 ,learning_rate =0.1,n_estimators=1000, min_child_weight = 1, gamma = 1)
model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=1, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=20,
              max_leaves=None, min_child_weight=1, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=1000,
              n_jobs=None, num_parallel_tree=None, ...)

In [18]:
# evaluate model
from sklearn.metrics import  f1_score, classification_report, confusion_matrix
y_pred = model.predict(x_test)
print(f1_score(y_test,y_pred))

0.9429626590069758

In [19]:
# predict test samples
submission = model.predict(test_data)
submission = pd.DataFrame(submission)
submission.columns = ['Cancel']
submission

       Cancel
0           0
1           0
2           0
3           1
4           0
...       ...
43288       0
43289       0
43290       0
43291       0
43292       0

[43293 rows x 1 columns]